### ISSUE TITLE
Add a chapter on testing

### ISSUE THREAD

**Issue by westurner** [scipy-lectures/scientific-python-lectures#126]
Science is largely the process of testing, confirming, and rejecting hypotheses in order to answer questions.

Test-Driven Development is strongly aligned with this objective.

A section on testing could be helpful?

**Comment by GaelVaroquaux** [comment]
If someone takes this up, I think that it's important not only to describe software issues, but also the thought process of testing, how to isolate subproblems for testing, tips and tricks for testing (for instance using io.BytesIO instead of files, to inspect what a routine does to a file.

**Comment by mattip** [comment]
Please use pytest instead of nosetests

**Comment by GaelVaroquaux** [comment]
> Please use pytest instead of nosetests

Sure!

Pull request welcome, by the way :).

**Comment by gertingold** [comment]
I have a chapter on testing in the lecture notes of a course I was teaching last winter term: http://gertingold.github.io/tools4scicomp/testing.html

It discusses some conceptual aspects of testing and then continues with an introduction to doctests and pytest. Would something like that be useful for the Scipy lecture notes at least to get started with a chapter on testing? Which aspects would need to be covered in addition?

**Comment by westurner** [comment]
I'd like to offer any of these verbatim or the points therein for a chapter
on testing, as well:

https://westurner.github.io/2016/10/18/criteria-for-success-and-test-driven-development

https://westurner.github.io/2016/10/17/teaching-test-driven-development-first.html

- Hypothesis testing
- Testing & refactoring: shape subclasses (OOP and/or functional paradigms)
Triangle(Shape);
Square(Rectangle(Quadrilateral (Parallelogram(Shape)))

Is it still TDD if we don't write the test and test that the test fails
first?
