### ISSUE TITLE
Get the epub sphinx builder to work

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scientific-python-lectures#140]
Sphinx has an epub builder. It would be awesome to be able to provide good epub (eg for reading on the kindle). I suspect that there will be work making sure that everything renders well.

**Comment by GaelVaroquaux** [comment]
"make epub" works more or less:

- The epub it produces seems to be readable by a small number of epub readers (but okular manages it)
- The layout is very broken and needs to be fixed.

**Comment by tiger2wander** [comment]
Hey, any update for epub build? It is very hard to read in pdf on Ebook reader (I'm using Kobo Aura H2O). Text is very small with large margin.

**Comment by GaelVaroquaux** [comment]
> Hey, any update for epub build?

No. It requires work (sphinx supports it, in theory). There is an epub
target in the Makefile, but it doesn't produce a readable epub. If you
want to take up the work to fix that, it would be fantastic.

**Comment by tiger2wander** [comment]
Sorry but I'm busy with projects, hope I can find sometime to take it soon.
