### ISSUE TITLE
wording in definition of t-test and p-value

### ISSUE THREAD

**Issue by jeromedockes** [scipy-lectures/scientific-python-lectures#410]
section 1.5.6.3 (overview of scipy.stats in the intro) proposes a definition of
a p-value:

  "the p value: the probability of both processes being identical. If it is close
  to 1, the two process are almost certainly identical. The closer it is to
  zero, the more likely it is that the processes have different means."

However the p-value is the probability of seeing an (absolute) difference
between the sample means that is as big or bigger than the one we observed,
given that the population means are equal. it is **not** the probability of the
null hypothesis being true; p being close to 1 does not mean the null is "almost
certainly" true; and p being small does not mean that the the null is "likely"
to be false.

similarly, the wording of the definition of a t-test in 3.1.2.1 can be confusing
for someone who is not familiar with this concept:

  "scipy.stats.ttest_1samp() tests if the population mean of data is likely to be
  equal to a given value"

**Comment by mdhaber** [comment]
Yes, I noticed this, too. I'll submit a PR shortly.

**Comment by mdhaber** [comment]
The issue in 1.5.6 was addressed by gh-585, and the issue in 3.1.2 was addressed by gh-592. I think this can be closed.
