### ISSUE TITLE
Section labels mismatch

### ISSUE THREAD

**Issue by rcolyer** [scipy-lectures/scientific-python-lectures#496]
The generated html files and pdf files have numerical section labels that do not match each other.  I was trying to curate a selection of sections for people to read, and I discovered that there is no reasonable way to do that across formats with the numbers contradicting.  The primary issue appears to be that the html goes from 1.7 to 2.1, while the pdf goes from I.7 to II.8, with the second values resetting for the html but not for the pdf.  It's arbitrary which one changes I suppose, but they should really be the same.  Matching up the format of the 1 and 2 with the I and II, would also be very reasonable.

**Comment by pdebuyl** [comment]
Hi @rcolyer thank you for giving feedback.

The issue is likely the sphinx LaTeX style that does not renumber chapters between parts while the html output does so. I will give it a look.
