### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by tupui** [scipy-lectures/scientific-python-lectures#587]
Since #574 got in, we can think about updating the hosting. I propose to do:

https://lectures.scientific-python.org

There is also a question about migrating the repository to Scientific Python's org.

**Comment by GaelVaroquaux** [comment]
> https://lectures.scientific-python.org

If we do this, we should do a permanent redirect (301 code https://en.wikipedia.org/wiki/HTTP_301) from http://scipy-lectures.org/, so that the search engine optimization and bookmarks carry over.

G

**Comment by tupui** [comment]
+1 to this, thank you Gael! I suppose we could also add a banner for folks using the old URL.

**Comment by stefanv** [comment]
xref: #656

**Comment by tupui** [comment]
Closing, all is done 🎉 Thank you folks =)
