### ISSUE TITLE
Argsort -> argmin

### ISSUE THREAD

**Issue by cebaa** [scipy-lectures/scientific-python-lectures#611]
http://scipy-lectures.org/intro/numpy/exercises.html#array-manipulations

> Harder one: Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.
>
> - Use abs and argsort to find the column j closest for each row.
> - Use fancy indexing to extract the numbers. (Hint: a[i,j] – the array i must contain the row numbers corresponding to stuff in j.)

Not sure if intentional, but the suggestion to use `argsort` instead of `argmin` seems strange, unless I'm missing a better solution than `numpy.argsort(a)[:, 0]`.

**Comment by rossbar** [comment]
It's a minor issue, but I find a solution with `argmin` easier to read as well. Consider opening a PR!

**Comment by jarrodmillman** [comment]
@cebaa A PR would be more than welcome!!
