### ISSUE TITLE
Building source in Windows

### ISSUE THREAD

**Issue by 50cop** [scipy-lectures/scientific-python-lectures#680]
Hello,
I am not able to generate html output from the source using Windows. My guess is that its because the source doesn't contain a make.bat file but I might be completly wrong (new to sphinx).
Do you have any idea on how to build the lectures in html in Windows?
Thank you for any tips!
Best

**Comment by jarrodmillman** [comment]
We don't support Windows for building the docs. The current version of the lecture notes are available here:
https://lectures.scientific-python.org/

**Comment by 50cop** [comment]
Noted. Thanks!
