### ISSUE TITLE
Finish up new numpy section

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scientific-python-lectures#94]
- [ ] In operations.rst, around line 209: the "data statistics" example 
    can probably be completely removed in my eyes (it is in the
    exercises.rst file).
- [ ] I'd really like the random walk example back in. I use it to teach 
    how a problem can be vectorized, rather than relying on for loops.
- [ ] The transpose remark should be put back in. It is a very important
    remark, in my experience.
- [ ] array_object.rst, line 767: I would keep the simple 'arange(10)'
    example, just for the sake of simplicity, unless I am missing the point.

**Comment by pdebuyl** [comment]
1. PR coming
2. You (@GaelVaroquaux ) already put the example back in :-)
3. The transpose example is correct since several versions of NumPy, see https://github.com/scipy-lectures/scipy-lecture-notes/issues/278
4. I have no idea where to look at in the current source file.

**Comment by pdebuyl** [comment]
To close up, I think we should merge the PR and remove the transpose warning.
